### ISSUE TITLE
Can this be adapted to an esp8266?

### ISSUE THREAD

**Issue by Maatooh** [GhostSonic21/SNES-Arduino-Controller-Emulator#1]
My intention is that a simple tcp or udp connection can be used to send and receive input from any device using a PC as an intermediary, and the esp8266 sends the data to the console, my problem is to implement the snes controller emulator on the esp8266, I have tried on my own taking several reference codes built for arduino uno but I am not successful as there are differences with this board, and I don't have enough experience with it.

If it is possible I am very interested, greetings.

**Comment by Maatooh** [comment]
I was able to implement it, but the B button doesn't stay on, it kind of blinks. has this happened to you?

**Comment by GhostSonic21** [comment]
@Maatooh Hey, just saw this. I haven't used an ESP8266 but the logic in the code is pretty simple. Not sure why the B button is ghosting on it, but it's the first sent over, so that probably has something to do with it.
